### ISSUE TITLE
PHP generics for Generator

### ISSUE THREAD

**Issue by szepeviktor** [mlocati/unipoints#7]
The return type of Generator is `Generator<string>`

**Comment by mlocati** [comment]
@szepeviktor I'm sorry I don't understand what you mean...

**Comment by szepeviktor** [comment]
Currently the Generator returns `string[]` which is incorrect.
https://github.com/mlocati/unipoints/blob/b75fc7a49a9e4ec40cc089dcbdaa8e59c3e77a4e/build/DataStorage.php#L60-L65

**Comment by mlocati** [comment]
Is #23 what you mean?
